### ISSUE TITLE
Move up 

### ISSUE THREAD

**Issue by robweir** [j4502/Editor-Staff-Hub#4]
[Reference](https://github.com/j4502/Editor-Staff-Hub/blob/develop/index.html#L33-L43)

So this really needs to be much higher on the page, like the first thing that people see when they get here. It would also be nice to add in the email addresses for these links so that people can email straight from their phones.

**Comment by mptacin** [comment]
Hey Rob, I can go ahead and add any relevant email addresses under the sections. I think we were hoping to make the Missourian Staff Editor Hub and all the tabs under it a clickable, horizontal header that's on top of the page so ultimately this section will be the first copy viewers see on the page. Do you think that's something we could achieve for the final project, or do you think we should just go ahead and move it up for the time being?

**Comment by robweir** [comment]
Hm. Why don't you move it up for now, and we'll worry about the tab thing once y'all learn some more css?

**Comment by mptacin** [comment]
Ok! And for the email addresses can they be on the same line as the phone # or is there a way to make a list inside an unordered list?

**Comment by mptacin** [comment]
Never mind I found a way, thanks!
