### ISSUE TITLE
Assets should have descriptive names

### ISSUE THREAD

**Issue by emilypstewart** [j4502/Editor-Staff-Hub#7]
[Reference](https://github.com/j4502/Editor-Staff-Hub/tree/feature-bios/assets/images)

Right now, it's hard to tell what a photo is without opening it up.

Consider `photo10.png` vs. `Elizabeth-Brixey.png`. 
Which is easier to debug if you're having trouble? I've found using descriptive names makes things a lot easier in the long run.

**Comment by srhm93** [comment]
Done!
